// frontend/src/App.tsx
import { useState, useEffect, useRef } from 'react';
import { Sidebar } from './components/Sidebar';
import { TopBar } from './components/TopBar';
import { ConnectionModal } from './components/ConnectionModal';
import { DataTable } from './components/DataTable';
import { QueryEditor } from './components/QueryEditor';
import type {ServerInfo, StoredServer} from '@shared/types/database';

function App() {
  const [servers, setServers] = useState<ServerInfo[]>([]);
  const [selectedServerId, setSelectedServerId] = useState<string | null>(null);
  const [selectedDatabase, setSelectedDatabase] = useState<string | null>(null);
  const [selectedTable, setSelectedTable] = useState<string | null>(null);
  const [activeTab, setActiveTab] = useState<'data' | 'query'>('query');
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingServer, setEditingServer] = useState<StoredServer | null>(null);
  const [loadingServers, setLoadingServers] = useState<string[]>([]);
  const [loadingDatabases, setLoadingDatabases] = useState<string[]>([]);
  const [sidebarWidth, setSidebarWidth] = useState(256); // Default in px
  const sidebarWidthRef = useRef(256);
  const [isResizing, setIsResizing] = useState(false);
  const [dbFilter, setDbFilter] = useState('');
  const [tableFilter, setTableFilter] = useState('');
  const [expandedServerIds, setExpandedServerIds] = useState<string[]>([]);
  const [expandedDatabaseIds, setExpandedDatabaseIds] = useState<string[]>([]);

  useEffect(() => {
    initApp();
  }, []);

  const initApp = async () => {
    // 1. Fetch stored servers
    const storedRes = await fetch('http://localhost:3001/api/stored-servers');
    const storedServers: StoredServer[] = await storedRes.json();

    // 2. Fetch app state
    const stateRes = await fetch('http://localhost:3001/api/app-state');
    const state = await stateRes.json();

    if (state) {
      // 3. Reconnect to previously active servers
      if (state.activeServerIds && state.activeServerIds.length > 0) {
        for (const serverId of state.activeServerIds) {
          const serverToConnect = storedServers.find(s => s.id === serverId);
          if (serverToConnect) {
            await handleConnect(serverToConnect, false); // No cerramos el modal ni refrescamos servers individualmente aquí
          }
        }
      }

      // 4. Restore state
      setSidebarWidth(state.sidebarWidth || 256);
      setDbFilter(state.dbFilter || '');
      setTableFilter(state.tableFilter || '');
      setSelectedServerId(state.selectedServerId);
      setSelectedDatabase(state.selectedDatabase);
      setSelectedTable(state.selectedTable);
      setActiveTab(state.activeTab || 'query');
      setExpandedServerIds(state.expandedServerIds || []);
      setExpandedDatabaseIds(state.expandedDatabaseIds || []);
    }

    await fetchServers();

    // 5. Expand restored servers and databases
    if (state) {
      if (state.expandedServerIds) {
        for (const sId of state.expandedServerIds) {
          handleExpandServer(sId);
        }
      }
      if (state.expandedDatabaseIds) {
        for (const dbId of state.expandedDatabaseIds) {
          const [sId, dbName] = dbId.split(':');
          if (sId && dbName) {
            handleExpandDatabase(sId, dbName);
          }
        }
      }
    }
  };

  useEffect(() => {
    const saveState = async () => {
      const state = {
        activeServerIds: servers.map(s => s.id),
        selectedServerId,
        selectedDatabase,
        selectedTable,
        activeTab,
        sidebarWidth,
        dbFilter,
        tableFilter,
        expandedServerIds,
        expandedDatabaseIds
      };

      try {
        await fetch('http://localhost:3001/api/app-state', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify(state),
        });
      } catch (error) {
        console.error('Error saving app state:', error);
      }
    };

    // Debounce state saving
    const timer = setTimeout(saveState, 1000);
    return () => clearTimeout(timer);
  }, [servers, selectedServerId, selectedDatabase, selectedTable, activeTab, sidebarWidth, dbFilter, tableFilter, expandedServerIds, expandedDatabaseIds]);

  useEffect(() => {
    if (isResizing) {
      window.addEventListener('mousemove', handleMouseMove);
      window.addEventListener('mouseup', handleMouseUp);
    } else {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    }
    return () => {
      window.removeEventListener('mousemove', handleMouseMove);
      window.removeEventListener('mouseup', handleMouseUp);
    };
  }, [isResizing]);

  useEffect(() => {
    sidebarWidthRef.current = sidebarWidth;
    document.documentElement.style.setProperty('--sidebar-width', `${sidebarWidth}px`);
  }, [sidebarWidth]);

  const handleMouseDown = (e: React.MouseEvent) => {
    e.preventDefault();
    setIsResizing(true);
  };

  const handleMouseMove = (e: MouseEvent) => {
    if (!isResizing) return;
    
    let newWidth = e.clientX;
    const minWidth = window.innerWidth * 0.05;
    const maxWidth = window.innerWidth * 0.20;
    
    if (newWidth < minWidth) newWidth = minWidth;
    if (newWidth > maxWidth) newWidth = maxWidth;
    
    sidebarWidthRef.current = newWidth;
    document.documentElement.style.setProperty('--sidebar-width', `${newWidth}px`);
  };

  const handleMouseUp = () => {
    if (isResizing) {
      setSidebarWidth(sidebarWidthRef.current);
    }
    setIsResizing(false);
  };

  const fetchServers = async () => {
    const res = await fetch('http://localhost:3001/api/servers');
    const data = await res.json();
    setServers(data);
  };

  const handleExpandServer = async (serverId: string) => {
    if (loadingServers.includes(serverId)) return;
    
    setLoadingServers(prev => [...prev, serverId]);
    try {
      const res = await fetch(`http://localhost:3001/api/servers/${serverId}/databases`);
      const databases = await res.json();
      
      setServers(prev => prev.map(s => 
        s.id === serverId ? { ...s, databases } : s
      ));
    } catch (error) {
      console.error('Error fetching databases:', error);
    } finally {
      setLoadingServers(prev => prev.filter(id => id !== serverId));
    }
  };

  const handleExpandDatabase = async (serverId: string, dbName: string) => {
    const key = `${serverId}:${dbName}`;
    if (loadingDatabases.includes(key)) return;

    setLoadingDatabases(prev => [...prev, key]);
    try {
      const res = await fetch(`http://localhost:3001/api/servers/${serverId}/databases/${dbName}/tables`);
      const tables = await res.json(); // Ahora es una lista de objetos {name, size}

      setServers(prev => prev.map(s => {
        if (s.id === serverId) {
          const updatedDbs = s.databases?.map(db => 
            db.name === dbName ? { 
              ...db, 
              tables, 
              size: tables.reduce((acc: number, t: any) => acc + (t.size || 0), 0) 
            } : db
          );
          return { ...s, databases: updatedDbs };
        }
        return s;
      }));
    } catch (error) {
      console.error('Error fetching tables:', error);
    } finally {
      setLoadingDatabases(prev => prev.filter(k => k !== key));
    }
  };

  const handleCloseModal = () => {
    setIsModalOpen(false);
    setEditingServer(null);
  };

  const handleConnect = async (storedServer: StoredServer, closeAndRefresh = true) => {
    const res = await fetch('http://localhost:3001/api/servers/connect', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(storedServer),
    });
    if (res.ok && closeAndRefresh) {
      await fetchServers();
      handleCloseModal();

      // Seleccionar el servidor recién conectado
      setSelectedServerId(storedServer.id);
      setSelectedDatabase(null);
      setSelectedTable(null);
      setActiveTab('query');

      // Expandir el servidor y cargar sus bases de datos
      setExpandedServerIds(prev => prev.includes(storedServer.id) ? prev : [...prev, storedServer.id]);
      handleExpandServer(storedServer.id);
    }
  };

  const handleCloseConnection = async () => {
    if (!selectedServerId) return;
    try {
      const res = await fetch(`http://localhost:3001/api/servers/${selectedServerId}`, {
        method: 'DELETE',
      });
      if (res.ok) {
        // Actualizamos localmente para una respuesta inmediata en la UI
        setServers(prev => prev.filter(s => s.id !== selectedServerId));
        setSelectedServerId(null);
        setSelectedDatabase(null);
        setSelectedTable(null);
      } else {
        const errorData = await res.json();
        alert('Error closing connection: ' + (errorData.error || 'Unknown error'));
      }
    } catch (error: any) {
      console.error('Error closing connection:', error);
      alert('Error closing connection: ' + error.message);
    }
  };

  const handleConfigServer = async (serverId: string) => {
    try {
      const res = await fetch('http://localhost:3001/api/stored-servers');
      const storedServers: StoredServer[] = await res.json();
      const serverToEdit = storedServers.find(s => s.id === serverId);
      if (serverToEdit) {
        setEditingServer(serverToEdit);
        setIsModalOpen(true);
      } else {
        alert('No se pudo encontrar la configuración guardada para este servidor.');
      }
    } catch (error) {
      console.error('Error fetching server config:', error);
    }
  };

  return (
    <div className={`flex h-screen w-screen bg-slate-950 text-slate-100 overflow-hidden ${isResizing ? 'cursor-col-resize select-none' : ''}`}>
      <Sidebar 
        servers={servers}
        selectedServerId={selectedServerId}
        selectedDatabase={selectedDatabase}
        selectedTable={selectedTable}
        dbFilter={dbFilter}
        tableFilter={tableFilter}
        setDbFilter={setDbFilter}
        setTableFilter={setTableFilter}
        onSelectServer={(id) => {
          setSelectedServerId(id);
          setSelectedDatabase(null);
          setSelectedTable(null);
          setActiveTab('query');
        }}
        onSelectDatabase={(serverId, db) => {
          setSelectedServerId(serverId);
          setSelectedDatabase(db);
          setSelectedTable(null);
          setActiveTab('query');
        }}
        onSelectTable={(serverId, db, table) => {
          setSelectedServerId(serverId);
          setSelectedDatabase(db);
          setSelectedTable(table);
          setActiveTab('data');
        }}
        onExpandServer={handleExpandServer}
        onExpandDatabase={handleExpandDatabase}
        expandedServerIds={expandedServerIds}
        setExpandedServerIds={setExpandedServerIds}
        expandedDatabaseIds={expandedDatabaseIds}
        setExpandedDatabaseIds={setExpandedDatabaseIds}
        onConfigServer={handleConfigServer}
        loadingServers={loadingServers}
        loadingDatabases={loadingDatabases}
        onResizeMouseDown={handleMouseDown}
        onOpenConnection={() => setIsModalOpen(true)}
      />
      <div className="flex-1 flex flex-col min-w-0">
        <TopBar 
          onOpenConnection={() => setIsModalOpen(true)}
          onCloseConnection={handleCloseConnection}
          canClose={!!selectedServerId}
        />
        <main className="flex-1 flex flex-col p-4 overflow-hidden min-w-0">
          {selectedServerId ? (
            <div className="w-full h-full flex flex-col min-h-0 min-w-0">
               {/* Tabs Header */}
               <div className="flex border-b border-slate-800 mb-4 flex-shrink-0">
                 {selectedTable && (
                   <button 
                    onClick={() => setActiveTab('data')}
                    className={`px-4 py-2 text-sm font-medium border-b-2 ${activeTab === 'data' ? 'border-blue-500 text-blue-500' : 'border-transparent text-slate-400 hover:text-slate-200'}`}
                   >
                     Datos
                   </button>
                 )}
                 <button 
                  onClick={() => setActiveTab('query')}
                  className={`px-4 py-2 text-sm font-medium border-b-2 ${activeTab === 'query' ? 'border-blue-500 text-blue-500' : 'border-transparent text-slate-400 hover:text-slate-200'}`}
                 >
                   Query
                 </button>
               </div>

               {/* Tab Content */}
               <div className="flex-1 min-h-0 flex flex-col min-w-0">
                 {activeTab === 'data' && selectedTable && selectedServerId && selectedDatabase && (
                    <DataTable 
                      serverId={selectedServerId}
                      database={selectedDatabase}
                      table={selectedTable}
                    />
                 )}
                 {activeTab === 'query' && (
                    <QueryEditor 
                      serverId={selectedServerId}
                      database={selectedDatabase}
                    />
                 )}
               </div>
            </div>
          ) : (
            <div className="flex-1 flex flex-col items-center justify-center">
              <div className="max-w-2xl text-center space-y-4">
                <h1 className="text-4xl font-bold text-blue-500">SQL Manager</h1>
                <p className="text-slate-400 text-lg">
                  Select a server, database and table from the sidebar to start managing your data.
                </p>
                <div className="grid grid-cols-2 gap-4 mt-8 mx-auto">
                  <div className="p-6 bg-slate-900 rounded-lg border border-slate-800 text-left">
                    <h3 className="font-semibold text-blue-400 mb-2">Modular Backend</h3>
                    <p className="text-sm text-slate-500">Ready for MySQL, PostgreSQL, and SQLite.</p>
                  </div>
                  <div className="p-6 bg-slate-900 rounded-lg border border-slate-800 text-left">
                    <h3 className="font-semibold text-blue-400 mb-2">Modern UI</h3>
                    <p className="text-sm text-slate-500">Built with React, Tailwind CSS and Lucide icons.</p>
                  </div>
                </div>
              </div>
            </div>
          )}
        </main>
      </div>

      {isModalOpen && (
        <ConnectionModal 
          onClose={handleCloseModal}
          onConnect={handleConnect}
          editServer={editingServer || undefined}
        />
      )}
    </div>
  )
}

export default App

// src/renderer/App.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, watch, computed, shallowRef } from 'vue';
import { Plus, X } from 'lucide-vue-next';
import Sidebar from './components/Sidebar.vue';
import TopBar from './components/TopBar.vue';
import ConnectionModal from './components/ConnectionModal.vue';
import SettingsModal from './components/SettingsModal.vue';
import ErrorModal from './components/ErrorModal.vue';
import DataTable from './components/DataTable.vue';
import TableSchema from './components/TableSchema.vue';
import QueryEditor from './components/QueryEditor.vue';
import { showError } from './errorService';
import { $t, setLocale } from './i18n';
import { api } from './services/api';
import type { ServerInfo, StoredServer, AppSettings } from '@shared/types/database';

const servers = shallowRef<ServerInfo[]>([]);
const selectedServerName = ref<string | null>(null);
const selectedDatabase = ref<string | null>(null);
const selectedTable = ref<string | null>(null);

const activeServerNames = computed(() => servers.value.map(s => s.name));

interface QueryTab {
  id: string;
  name: string;
  query: string;
}

const queryTabs = ref<QueryTab[]>([
  { id: '1', name: $t('query_editor.name_default') || 'Query 1', query: '' }
]);
const activeTab = ref<string>('1');
const editingTabId = ref<string | null>(null);
const editTabNameValue = ref('');

const vFocus = {
  mounted: (el: HTMLElement) => el.focus()
};
const isModalOpen = ref(false);
const isSettingsOpen = ref(false);
const editingServer = ref<StoredServer | undefined>(undefined);
const loadingServers = ref<string[]>([]);
const loadingDatabases = ref<string[]>([]);
const sidebarWidth = ref(256);
const isResizing = ref(false);
const dbFilter = ref('');
const tableFilter = ref('');
const expandedServerNames = ref<string[]>([]);
const expandedDatabaseIds = ref<string[]>([]);
const expandedTableIds = ref<string[]>([]);
const loadingTables = ref<string[]>([]);
const queryEditorHeight = ref(300);
const tableSchemaHeight = ref(400);

const fetchServers = async () => {
  const data = await api.getServers();
  servers.value = data;
};

const handleExpandServer = async (serverName: string) => {
  if (loadingServers.value.includes(serverName)) return;
  
  loadingServers.value.push(serverName);
  try {
    const databases = await api.getDatabases(serverName);
    
    servers.value = servers.value.map(s => 
      s.name === serverName ? { ...s, databases } : s
    );
  } catch (error: any) {
    console.error('Error fetching databases:', error);
    showError($t('sidebar.error_databases'), error.message);
  } finally {
    loadingServers.value = loadingServers.value.filter(id => id !== serverName);
  }
};

const handleExpandDatabase = async (serverName: string, dbName: string) => {
  const key = `${serverName}:${dbName}`;
  if (loadingDatabases.value.includes(key)) return;

  loadingDatabases.value.push(key);
  try {
    const tables = await api.getTables(serverName, dbName);

    servers.value = servers.value.map(s => {
      if (s.name === serverName) {
        const updatedDbs = s.databases?.map(db => 
          db.name === dbName ? { 
            ...db, 
            tables, 
            size: tables.reduce((acc: number, t: any) => acc + (t.size || 0), 0) 
          } : db
        );
        return { ...s, databases: updatedDbs };
      }
      return s;
    });
  } catch (error: any) {
    console.error('Error fetching tables:', error);
    showError($t('sidebar.error_tables'), error.message);
  } finally {
    loadingDatabases.value = loadingDatabases.value.filter(k => k !== key);
  }
};

const handleExpandTable = async (serverName: string, dbName: string, tableName: string) => {
  const key = `${serverName}:${dbName}:${tableName}`;
  if (loadingTables.value.includes(key)) return;

  loadingTables.value.push(key);
  try {
    const columns = await api.getColumns(serverName, dbName, tableName);

    servers.value = servers.value.map(s => {
      if (s.name === serverName) {
        const updatedDbs = s.databases?.map(db => {
          if (db.name === dbName) {
            const updatedTables = db.tables?.map(t => 
              t.name === tableName ? { ...t, columns } : t
            );
            return { ...db, tables: updatedTables };
          }
          return db;
        });
        return { ...s, databases: updatedDbs };
      }
      return s;
    });
  } catch (error: any) {
    console.error('Error fetching columns:', error);
    showError($t('sidebar.error_columns'), error.message);
  } finally {
    loadingTables.value = loadingTables.value.filter(k => k !== key);
  }
};

const handleConnect = async (storedServer: StoredServer, closeAndRefresh = true) => {
  try {
    await api.connect(storedServer);
    
    if (closeAndRefresh) {
      await fetchServers();
      isModalOpen.value = false;
      editingServer.value = undefined;

      selectedServerName.value = storedServer.name;
      selectedDatabase.value = null;
      selectedTable.value = null;
      
      // Seleccionar la primera pestaña de query disponible
      if (queryTabs.value.length > 0) {
        activeTab.value = queryTabs.value[0].id;
      }

      if (!expandedServerNames.value.includes(storedServer.name)) {
        expandedServerNames.value.push(storedServer.name);
      }
      void handleExpandServer(storedServer.name);
    }
  } catch (error: any) {
    console.error('Connection error:', error);
    const raw: string = error.message || 'Error desconocido';
    const msg = raw.replace(/^Error invoking remote method '[^']+': (Error: )?/, '');
    showError($t('conn_modal.error_connect'), msg);
  }
};

const initApp = async () => {
  await loadSettings();

  const storedServers: StoredServer[] = await api.getStoredServers();
  const state = await api.getAppState();

  if (state) {
    if (state.activeServerNames && state.activeServerNames.length > 0) {
      for (const serverName of state.activeServerNames) {
        const serverToConnect = storedServers.find(s => s.name === serverName);
        if (serverToConnect) {
          await handleConnect(serverToConnect, false);
        }
      }
    }

    sidebarWidth.value = state.sidebarWidth || 256;
    queryEditorHeight.value = state.queryEditorHeight || 300;
    tableSchemaHeight.value = state.tableSchemaHeight || 400;
    dbFilter.value = state.dbFilter || '';
    tableFilter.value = state.tableFilter || '';
    selectedServerName.value = state.selectedServerName;
    selectedDatabase.value = state.selectedDatabase;
    selectedTable.value = state.selectedTable;
    if (state.queryTabs && state.queryTabs.length > 0) {
      queryTabs.value = state.queryTabs;
    }
    activeTab.value = state.activeTab || queryTabs.value[0].id;
    
    // Validar que la pestaña activa existe
    if (activeTab.value !== 'data' && activeTab.value !== 'schema' && !queryTabs.value.find(t => t.id === activeTab.value)) {
      activeTab.value = queryTabs.value[0].id;
    }
    expandedServerNames.value = state.expandedServerNames || [];
    expandedDatabaseIds.value = state.expandedDatabaseIds || [];
    expandedTableIds.value = state.expandedTableIds || [];
  }

  await fetchServers();

  if (state) {
    if (state.expandedServerNames) {
      for (const sName of state.expandedServerNames) {
        void handleExpandServer(sName);
      }
    }
    if (state.expandedDatabaseIds) {
      for (const dbId of state.expandedDatabaseIds) {
        const [sName, dbName] = dbId.split(':');
        if (sName && dbName) {
          void handleExpandDatabase(sName, dbName);
        }
      }
    }
    if (state.expandedTableIds) {
      for (const tableId of state.expandedTableIds) {
        const [sName, dbName, tableName] = tableId.split(':');
        if (sName && dbName && tableName) {
          void handleExpandTable(sName, dbName, tableName);
        }
      }
    }
  }
};

const loadSettings = async () => {
  try {
    const settings: AppSettings = await api.getAppSettings();
    setLocale(settings.language || 'auto');
    applyTheme(settings.theme || 'system');
  } catch (err) {
    console.error('Failed to load settings:', err);
    setLocale('auto');
    applyTheme('system');
  }
};

const applyTheme = (theme: AppSettings['theme']) => {
  const isDark = theme === 'dark' || (theme === 'system' && window.matchMedia('(prefers-color-scheme: dark)').matches);
  if (isDark) {
    document.documentElement.classList.add('dark');
  } else {
    document.documentElement.classList.remove('dark');
  }
};

let themeChangeHandler: (() => void) | null = null;

onMounted(() => {
  initApp();
  document.documentElement.style.setProperty('--sidebar-width', `${sidebarWidth.value}px`);

  const mediaQuery = window.matchMedia('(prefers-color-scheme: dark)');
  themeChangeHandler = () => {
    api.getAppSettings().then((settings: AppSettings) => {
      if (!settings.theme || settings.theme === 'system') {
        applyTheme('system');
      }
    });
  };
  mediaQuery.addEventListener('change', themeChangeHandler);
});

onUnmounted(() => {
  if (themeChangeHandler) {
    window.matchMedia('(prefers-color-scheme: dark)').removeEventListener('change', themeChangeHandler);
    themeChangeHandler = null;
  }
});

watch([activeServerNames, selectedServerName, selectedDatabase, selectedTable, activeTab, sidebarWidth, queryEditorHeight, tableSchemaHeight, dbFilter, tableFilter, expandedServerNames, expandedDatabaseIds, expandedTableIds, queryTabs], (_, __, onCleanup) => {
  const saveState = async () => {
    const state = {
      activeServerNames: activeServerNames.value,
      selectedServerName: selectedServerName.value,
      selectedDatabase: selectedDatabase.value,
      selectedTable: selectedTable.value,
      activeTab: activeTab.value,
      queryTabs: queryTabs.value,
      sidebarWidth: sidebarWidth.value,
      queryEditorHeight: queryEditorHeight.value,
      tableSchemaHeight: tableSchemaHeight.value,
      dbFilter: dbFilter.value,
      tableFilter: tableFilter.value,
      expandedServerNames: expandedServerNames.value,
      expandedDatabaseIds: expandedDatabaseIds.value,
      expandedTableIds: expandedTableIds.value
    };

    try {
      await api.saveAppState(state);
    } catch (error) {
      console.error('Error saving app state:', error);
    }
  };

  const timer = setTimeout(saveState, 1000);
  onCleanup(() => clearTimeout(timer));
}, { deep: true });

const handleMouseMove = (e: MouseEvent) => {
  if (!isResizing.value) return;
  
  let newWidth = e.clientX;
  const minWidth = window.innerWidth * 0.05;
  const maxWidth = window.innerWidth * 0.20;
  
  if (newWidth < minWidth) newWidth = minWidth;
  if (newWidth > maxWidth) newWidth = maxWidth;
  
  document.documentElement.style.setProperty('--sidebar-width', `${newWidth}px`);
  sidebarWidth.value = newWidth;
};

const handleMouseUp = () => {
  isResizing.value = false;
  window.removeEventListener('mousemove', handleMouseMove);
  window.removeEventListener('mouseup', handleMouseUp);
};

const handleMouseDown = (e: MouseEvent) => {
  e.preventDefault();
  isResizing.value = true;
  window.addEventListener('mousemove', handleMouseMove);
  window.addEventListener('mouseup', handleMouseUp);
};

const handleCloseConnection = async () => {
  if (!selectedServerName.value) return;
  try {
    await api.disconnectServer(selectedServerName.value);
    servers.value = servers.value.filter(s => s.name !== selectedServerName.value);
    selectedServerName.value = null;
    selectedDatabase.value = null;
    selectedTable.value = null;
  } catch (error: any) {
    console.error('Error closing connection:', error);
    showError($t('topbar.error_close_conn'), error.message);
  }
};

const handleConfigServer = async (serverName: string) => {
  try {
    const storedServers: StoredServer[] = await api.getStoredServers();
    const serverToEdit = storedServers.find(s => s.name === serverName);
    if (serverToEdit) {
      editingServer.value = serverToEdit;
      isModalOpen.value = true;
    } else {
      showError($t('sidebar.error_config_not_found_title'), $t('sidebar.error_config_not_found_msg'));
    }
  } catch (error: any) {
    console.error('Error fetching server config:', error);
    showError($t('sidebar.error_get_config'), error.message);
  }
};

const lastActiveQueryTabId = ref<string>('1');

watch(activeTab, (newVal) => {
  if (newVal !== 'data' && newVal !== 'schema') {
    lastActiveQueryTabId.value = newVal;
  }
});

const addQueryTab = () => {
  const newId = Date.now().toString();
  queryTabs.value = [
    ...queryTabs.value,
    {
      id: newId,
      name: `Query ${queryTabs.value.length + 1}`,
      query: ''
    }
  ];
  activeTab.value = newId;
};

const startEditingTabName = (tab: QueryTab) => {
  editingTabId.value = tab.id;
  editTabNameValue.value = tab.name;
};

const saveTabName = () => {
  if (editingTabId.value) {
    queryTabs.value = queryTabs.value.map(t => {
      if (t.id === editingTabId.value) {
        const newName = editTabNameValue.value.trim();
        return newName ? { ...t, name: newName } : t;
      }
      return t;
    });
  }
  editingTabId.value = null;
};

const removeQueryTab = (id: string) => {
  if (queryTabs.value.length <= 1) return;
  const index = queryTabs.value.findIndex(t => t.id === id);
  queryTabs.value = queryTabs.value.filter(t => t.id !== id);
  if (activeTab.value === id) {
    activeTab.value = queryTabs.value[Math.max(0, index - 1)].id;
  }
};

const selectServer = (name: string) => {
  selectedServerName.value = name;
  selectedDatabase.value = null;
  selectedTable.value = null;
  if (activeTab.value === 'data' || activeTab.value === 'schema') {
    activeTab.value = lastActiveQueryTabId.value;
  }
};

const selectedServerType = computed(() => {
  const server = servers.value.find(s => s.name === selectedServerName.value);
  return server?.type || 'mysql';
});

const selectDatabase = (serverName: string, db: string) => {
  selectedServerName.value = serverName;
  selectedDatabase.value = db;
  selectedTable.value = null;
  if (activeTab.value === 'data' || activeTab.value === 'schema') {
    activeTab.value = lastActiveQueryTabId.value;
  }
};

const selectTable = (serverName: string, db: string, table: string) => {
  selectedServerName.value = serverName;
  selectedDatabase.value = db;
  selectedTable.value = table;
  activeTab.value = 'schema';
};
</script>

<template>
  <div class="flex h-screen w-screen bg-slate-50 dark:bg-slate-950 text-slate-900 dark:text-slate-100 overflow-hidden" :class="isResizing ? 'cursor-col-resize select-none' : ''">
    <Sidebar 
      :servers="servers"
      :selectedServerName="selectedServerName"
      :selectedDatabase="selectedDatabase"
      :selectedTable="selectedTable"
      v-model:dbFilter="dbFilter"
      v-model:tableFilter="tableFilter"
      v-model:expandedServerNames="expandedServerNames"
      v-model:expandedDatabaseIds="expandedDatabaseIds"
      v-model:expandedTableIds="expandedTableIds"
      @selectServer="selectServer"
      @selectDatabase="selectDatabase"
      @selectTable="selectTable"
      @expandServer="handleExpandServer"
      @expandDatabase="handleExpandDatabase"
      @expandTable="handleExpandTable"
      @configServer="handleConfigServer"
      :loadingServers="loadingServers"
      :loadingDatabases="loadingDatabases"
      :loadingTables="loadingTables"
      @resizeMouseDown="handleMouseDown"
      @openConnection="isModalOpen = true"
    />
    <div class="flex-1 flex flex-col min-w-0">
      <TopBar 
        @openConnection="isModalOpen = true"
        @closeConnection="handleCloseConnection"
        @openSettings="isSettingsOpen = true"
        :canClose="!!selectedServerName"
      />
      <main class="flex-1 flex flex-col p-4 overflow-hidden min-w-0">
        <div v-if="selectedServerName" class="w-full h-full flex flex-col min-h-0 min-w-0">
          <!-- Tabs Header -->
          <div class="flex border-b border-slate-200 dark:border-slate-800 mb-4 flex-shrink-0 items-center overflow-x-auto scrollbar-none">
            <button 
              v-if="selectedTable"
              @click="activeTab = 'schema'"
              class="px-4 py-2 text-sm font-medium border-b-2 whitespace-nowrap transition-colors"
              :class="activeTab === 'schema' ? 'border-blue-500 text-blue-500 bg-blue-500/5' : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800/50'"
            >
              {{ $t('data_table.schema') }}
            </button>
            <button 
              v-if="selectedTable"
              @click="activeTab = 'data'"
              class="px-4 py-2 text-sm font-medium border-b-2 whitespace-nowrap transition-colors"
              :class="activeTab === 'data' ? 'border-blue-500 text-blue-500 bg-blue-500/5' : 'border-transparent text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200 hover:bg-slate-100 dark:hover:bg-slate-800/50'"
            >
              {{ $t('data_table.data') }}
            </button>
            <div 
              v-for="tab in queryTabs" 
              :key="tab.id"
              v-memo="[tab.id, tab.name, activeTab === tab.id, editingTabId === tab.id]"
              class="group relative flex items-center border-b-2 transition-colors"
              :class="(activeTab === tab.id || editingTabId === tab.id) ? 'border-blue-500 bg-blue-500/5' : 'border-transparent hover:bg-slate-100 dark:hover:bg-slate-800/50'"
            >
              <button 
                v-if="editingTabId !== tab.id"
                @click="activeTab = tab.id"
                @dblclick="startEditingTabName(tab)"
                class="pl-4 pr-2 py-2 text-sm font-medium whitespace-nowrap"
                :class="activeTab === tab.id ? 'text-blue-500' : 'text-slate-500 dark:text-slate-400 hover:text-slate-900 dark:hover:text-slate-200'"
              >
                {{ tab.name }}
              </button>
              <input
                v-else
                v-model="editTabNameValue"
                @blur="saveTabName"
                @keyup.enter="saveTabName"
                @keyup.escape="editingTabId = null"
                v-focus
                class="px-4 py-2 text-sm font-medium bg-slate-100 dark:bg-slate-800 text-blue-500 outline-none w-32"
              />
              <button 
                v-if="queryTabs.length > 1"
                @click.stop="removeQueryTab(tab.id)"
                class="mr-1.5 p-1 text-slate-400 dark:text-slate-500 hover:text-red-600 dark:hover:text-red-400 hover:bg-slate-200 dark:hover:bg-slate-700/50 rounded transition-all opacity-0 group-hover:opacity-100"
                :title="$t('query_editor.close_tab_title')"
              >
                <X :size="14" />
              </button>
            </div>
            <button 
              @click="addQueryTab"
              class="px-4 py-2 text-slate-500 dark:text-slate-400 hover:text-blue-500 hover:bg-slate-100 dark:hover:bg-slate-800/50 transition-colors border-b-2 border-transparent"
              :title="$t('query_editor.new_tab_title')"
            >
              <Plus :size="18" />
            </button>
          </div>

          <!-- Tab Content -->
          <div class="flex-1 min-h-0 flex flex-col min-w-0">
            <KeepAlive>
              <TableSchema 
                v-if="activeTab === 'schema' && selectedTable && selectedServerName && selectedDatabase"
                :key="`schema:${selectedServerName}:${selectedDatabase}:${selectedTable}`"
                :serverName="selectedServerName"
                :database="selectedDatabase"
                :table="selectedTable"
                v-model:height="tableSchemaHeight"
              />
            </KeepAlive>
            <KeepAlive>
              <DataTable 
                v-if="activeTab === 'data' && selectedTable && selectedServerName && selectedDatabase"
                :key="`data:${selectedServerName}:${selectedDatabase}:${selectedTable}`"
                :serverName="selectedServerName"
                :serverType="selectedServerType"
                :database="selectedDatabase"
                :table="selectedTable"
              />
            </KeepAlive>
            <KeepAlive>
              <QueryEditor 
                v-if="activeTab !== 'data' && activeTab !== 'schema'"
                :key="activeTab"
                :serverName="selectedServerName!"
                :serverType="selectedServerType"
                :database="selectedDatabase"
                v-model="queryTabs.find(t => t.id === activeTab)!.query"
                v-model:height="queryEditorHeight"
              />
            </KeepAlive>
          </div>
        </div>
        <div v-else class="flex-1 flex flex-col items-center justify-center">
          <div class="max-w-2xl text-center space-y-4">
            <h1 class="text-4xl font-bold text-blue-600 dark:text-blue-500">{{ $t('welcome.title') }}</h1>
            <p class="text-slate-600 dark:text-slate-400 text-lg">
              {{ $t('welcome.subtitle') }}
            </p>
            <div class="grid grid-cols-2 gap-4 mt-8 mx-auto">
              <div class="p-6 bg-white dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-800 text-left">
                <h3 class="font-semibold text-blue-600 dark:text-blue-400 mb-2">{{ $t('welcome.feature_backend_title') }}</h3>
                <p class="text-sm text-slate-500 dark:text-slate-500">{{ $t('welcome.feature_backend_desc') }}</p>
              </div>
              <div class="p-6 bg-white dark:bg-slate-900 rounded-lg border border-slate-200 dark:border-slate-800 text-left">
                <h3 class="font-semibold text-blue-600 dark:text-blue-400 mb-2">{{ $t('welcome.feature_ui_title') }}</h3>
                <p class="text-sm text-slate-500 dark:text-slate-500">{{ $t('welcome.feature_ui_desc') }}</p>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>

    <ConnectionModal 
      v-if="isModalOpen"
      @close="isModalOpen = false; editingServer = undefined"
      @connect="handleConnect"
      :editServer="editingServer"
    />
    <SettingsModal
      v-if="isSettingsOpen"
      @close="isSettingsOpen = false"
      @updated="loadSettings"
    />
    <ErrorModal />
  </div>
</template>
